version: '3.8'
services:
  app:
    build: .docker/php
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
  db:
    image: jacobalberty/firebird:3.0
    environment:
      - ISC_PASSWORD=masterkey
    volumes:
      - ./data:/firebird/data
